config-cat:
  sdk-key: GRbZCAbLN0-Ip9vQvHHGTg/FGehI9MhEEmSaA4fgDXb_g

cloud:
  aws:
    stack: false
    stack.auto: false
    credentials:
      access-key: test
      secret-key: test
    region:
      static: us-east-1
    end-point:
      uri: http://localhost:4566


spring:
  rabbitmq:
    publisher-confirm: true
    publisher-confirm-type: correlated
    publisher-return: true
    template:
      mandatory: true
    port: 5672
    username: guest
    password: guest
    host: localhost
    listener:
      prefetch: 2

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error