spring:
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: NEVER
  datasource:
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=FALSE;DB_CLOSE_ON_EXIT=FALSE
    username:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
